### ISSUE TITLE
Trigger on sidebar.js

### ISSUE THREAD

**Issue by danilowoz** [olvyhq/docusaurus-integration-example#1]
Hey @nshntarora, thanks for creating this example repository, I could make some progress on my side. However, I'd like to add the trigger in the `sidebar.js` instead of in the navbar. Unfortunately, Docusaurus doesn't provide a way to add custom ids in these items ([see here](https://github.com/codesandbox/sandpack/pull/330/files#diff-ea240d693ec49f75399dbbda35504d95150ebd65ebbae17f1c5e29ec87b11d51R23-R28)). 

So, in order to solve this problem I can see two approaches:
- Olvy provides an API to select custom elements in the document, instead of a single id;
- I workaround and add a listener to the given selector, but in this way, I'll lose all the others functionalities from the widget: 

```js
document.querySelector(".olvy-target").addEventListener("click", () => {
  OlvyUtils.showWidget('codesandbox', 'sandpack_widget')
})
```  

Hope we can make it work, let me know if you've found another way to attach ids to the sidebar

**Comment by nshntarora** [comment]
Hey @danilowoz,

You can set any selector in the Olvy widget builder UI. Anything that is a valid input for `document.querySelector` is a valid input for the widget target.

**Comment by danilowoz** [comment]
Thanks for answering. 
Could you please give an example? I couldn't make it work

**Comment by nshntarora** [comment]
Hi @danilowoz,

It's breaking because the target element configured for this widget on your Olvy dashboard (at app.olvy.co) is `#olvy-sandpack-widget`, if you change it to `.olvy-target` the widget will work (I've verified it locally by running your linked PR)

https://user-images.githubusercontent.com/8947356/153769264-c5c31e4d-5f0f-4cdd-ab28-3ff3b38cd3b8.mov

I believe you should be able to override a configuration while integrating a widget too. Will probably add a way to override the target selector in the `OlvyConfig` variable. Meanwhile, changing it on the dashboard should work.

**Comment by danilowoz** [comment]
ohh I didn't note that there's a target configuration on the dashboard, so it looks good now. I agree, that it would be great to have a way to override it - the closer to the code the better.

Thanks a lot @nshntarora
